### PR TITLE
Create greetings.yaml

### PR DESCRIPTION
**Pull request by sanmarg**
Added for #106

### CODE REVIEW

**Comment by joyhughes** [comment]
I have made some small changes. When Discord channels are ready I will add a request to join. PR is approved.

**Comment by rudi-cilibrasi** [comment]
Convention is for author to merge PR's https://softwareengineering.stackexchange.com/questions/334488/code-review-workflow-where-pull-request-author-must-merge

**Comment by rudi-cilibrasi** [comment]
@sanmarg i saw you like docker in your blog. this project uses Docker for cicd but it only does one kind of build using clang-12. it needs to also install react or vite dependencies in the docker image and then devs can run the react or vite frontend webserver using docker with a tcp port hole punch in say port 3000 or maybe --net=host

i just wanted to mention the need to you in case you are interested. there is also a need for an emscripten build (in addition to the clang-12 build we already check in cicd) to go into the react/vite frontend. ideally devs can then run docker container locally to see the changes they are making work etc

**Comment by sanmarg** [comment]
Sure I'll look into it

**Pull request merged**
