### PR TITLE
Added ESlint configuration to fix 'Maximum call stack size exceeded' …

### PR DESCRIPTION
**Pull request by Tasnuva12**
I have got this error  after starting the react app with the  command npm start :  
p1
I've added an ESLint configuration file to enforce linting rules, specifically disabling the "no-octal-escape" rule. This change resolves the linting error and ensures code consistency.

What I have done : 
1. created a file : eslint.config.js
2. Disabled "no-octal-escape" rule to fix the error in lux.js

### CODE REVIEW

**Comment by joyhughes** [comment]
@Tasnuva12 

I have not been able to reproduce this error. It may be dependent on your configuration.
When you fix this error does the React app run properly for you?

**Comment by Tasnuva12** [comment]
yes mam.

**Comment by joyhughes** [comment]
> yes mam.

Okay I'll push since others may encounter this problem

**Comment by Tasnuva12** [comment]
Hello, I did this pull request under girls summer script, I hope this will be added in my leadership board.

**Comment by joyhughes** [comment]
> Hello, I did this pull request under girls summer script, I hope this will be added in my leadership board.

I have added the necessary tags - hope this works for you

**Pull request merged**
