### PR TITLE
add emscripten build test

### PR DESCRIPTION
**Pull request by rudi-cilibrasi**
add emscripten build test to cicd

### CODE REVIEW

**Comment by joyhughes** [comment]
Makefile had dependency nebula_files/random_copy.json ... Better to have a re-link any time anything in nebula_files changes.

**Comment by joyhughes** [comment]
The contents of nebula_files are rolled into lux.js by the emcc link step. It's also probably best to give the directory a more generic name.

**Comment by rudi-cilibrasi** [comment]
this PR is probably a step forward even though it still doesn't link. i think it's good to merge this before embarking on new ideas as this fixes several clear syntax / C++ errors.

**Comment by rudi-cilibrasi** [comment]
https://github.com/search?q=repo%3Ajoyhughes%2FJen%20random_copy.json&type=code

**Comment by rudi-cilibrasi** [comment]
that file you mention is broken anyway its not in the repo as the search link shows

**Review by joyhughes — APPROVED** [review]
Go ahead and merge and I will immediately make another PR to fix build test on Emscripten.

**Comment by joyhughes** [comment]
> that file you mention is broken anyway its not in the repo as the search link shows

Right. Need to get rid of that dependency. Hopefully that will fix the build. However...

With no dependency on nebula_files, build can succeed as "nothing to be done" but if something in the directory has changed (most commonly the scene file), the result can be incorrect or break. (I found out how to check in makefile if any of the files have changed, but not if files have been added or deleted.)

**Comment by rudi-cilibrasi** [comment]
looks like i do not have merge power so you better hit the merge button for me now please Joy

**Comment by joyhughes** [comment]
> looks like i do not have merge power so you better hit the merge button for me now please Joy

Oh geez maybe I can set it differently

**Comment by joyhughes** [comment]
It seems I had restricted changes to collaborators to prevent the students from merging willy-nilly. I invited you as collaborator so you'll be able to do stuff again - I think that's essential.

**Pull request merged**
